
### 1. Spisak predmeta na studijskom programu - Program 1
GET http://localhost:8090/api/predmeti/studijski-program/1
Accept: application/json

###

### 2. Spisak predmeta na studijskom programu - Program 2
GET http://localhost:8090/api/predmeti/studijski-program/2
Accept: application/json

###

### 3. Spisak svih predmeta sa svim podacima
GET http://localhost:8090/api/predmeti/all
Accept: application/json

###

### 4. Dodavanje novog predmeta sa jedinstvenom šifrom
POST http://localhost:8090/api/predmeti/add
Content-Type: application/json

{
  "sifra": "NEWPRED",
  "naziv": "Novi Predmet",
  "opis": "Opis novog predmeta",
  "espb": 6,
  "studijskiProgramId": 1,
  "obavezan": true
}

###

### 5. Pokušaj dodavanja predmeta sa postojećom šifrom (greška)
POST http://localhost:8090/api/predmeti/add
Content-Type: application/json

{
  "sifra": "PR1",
  "naziv": "Duplikat",
  "opis": "Ovo treba da baci grešku",
  "espb": 6,
  "obavezan": true
}

###

### 6. Prosečna ocena na predmetu PR1 za period 2020-2024
GET http://localhost:8090/api/predmeti/1/prosecna-ocena?odGodine=2020&doGodine=2024
Accept: application/json

###

### 7. Prosečna ocena na predmetu PR2 za period 2023-2024
GET http://localhost:8090/api/predmeti/2/prosecna-ocena?odGodine=2023&doGodine=2024
Accept: application/json

###

### 8. Prosečna ocena za predmet bez polaganja
GET http://localhost:8090/api/predmeti/10/prosecna-ocena?odGodine=2020&doGodine=2024
Accept: application/json

###

### 9. Prosečna ocena - Nepostojeći predmet (404)
GET http://localhost:8090/api/predmeti/99999/prosecna-ocena?odGodine=2020&doGodine=2024
Accept: application/json

###

### 10. Spisak predmeta - Nepostojeći studijski program (404)
GET http://localhost:8090/api/predmeti/studijski-program/99999
Accept: application/json

###