# Server API URL
api.base.url=http://localhost:8090/api

# Navigation History
navigation.max.history=10

# Async Thread Pool
async.thread.pool.size=5

# Logging
logging.level.org.raflab.studsluzba.client=INFO
logging.level.org.raflab.studsluzba.client.navigation=DEBUG